#pragma once

#include "AbsCelestialObject.h"
#include "Camera.h"
#include "CelestialBody.h"
#include "CosmosRenderer.h"
#include "FrustumCone.h"
#include "GalaxyContainer.h"
#include "Model3d.h"
#include "RenderedCelestialBody.h"
#include "SceneProvider.h"
#include "Star.h"
#include "StarsRenderer.h"
#include "SubdividedMeshesProvider.h"
#include "OutputScreenRenderer.h"