#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(local_size_x = 256, local_size_y = 2, local_size_z = 1) in;

#include sphereRaytracing.glsl
#include celestialDataStructs.glsl
#include celestialShadowMapSet.glsl

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    vec2 resolution = celestialBuffer.time_dataresolution.yz;
    vec2 UV = vec2(pixel) / vec2(resolution);

    RenderedCelestialBody body = getRenderedBody(celestialBuffer.celestialBody);

}
